"""
models.py — Clustering Algorithms & Evaluation Metrics Module

This module provides functions for running clustering algorithms (K-Means,
DBSCAN, Agglomerative Hierarchical) on preprocessed RFM features and
evaluating the quality of the resulting clusters.

Key Exports:
    - plot_elbow(data, max_k):              Plots the Elbow curve (inertia vs. k)
                                             to help determine optimal K for K-Means.
    - run_kmeans(data, k):                  Runs K-Means clustering and returns labels.
    - run_dbscan(data, eps, min_samples):   Runs DBSCAN clustering and returns labels.
    - run_hierarchical(data, n_clusters, linkage_method):
                                             Runs Agglomerative Hierarchical Clustering
                                             and returns labels.
    - plot_dendrogram(data, method, max_display):
                                             Plots a dendrogram to visualize the
                                             hierarchical cluster structure.
    - calculate_silhouette(data, labels):   Computes the Silhouette Score for
                                             cluster quality evaluation.
"""

# =============================================================================
# Imports
# =============================================================================

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage


# =============================================================================
# Visualization Functions
# =============================================================================


def plot_elbow_kmeans(data, max_k=10):
    """
    Plot the Elbow curve to find the optimal number of clusters for K-Means.

    The Elbow Method plots the total within-cluster sum of squares (inertia)
    against different values of k.  The "elbow" point — where inertia starts
    to decrease more slowly — suggests a good balance between model complexity
    and fit.

    Args:
        data (array-like): Preprocessed feature matrix (e.g., scaled RFM values).
            Should be a 2D array or DataFrame with shape (n_samples, n_features).
        max_k (int): Maximum number of clusters to evaluate. Defaults to 10.
            The function tests k = 1, 2, ..., max_k.

    Returns:
        None: Displays the Elbow plot inline.
    """
    inertia = []
    k_range = range(1, max_k + 1)

    # Fit K-Means for each value of k and record the inertia
    for k in k_range:
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit(data)
        inertia.append(kmeans.inertia_)

    # Plot the Elbow curve
    plt.figure(figsize=(10, 6))
    plt.plot(k_range, inertia, marker="o", linestyle="--", color="#2e86c1")
    plt.title("Elbow Method for Optimal K", fontsize=14)
    plt.xlabel("Number of Clusters (k)", fontsize=12)
    plt.ylabel("Inertia", fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.show()


def plot_rfm_clusters(rfm_df, cluster_labels, cluster_names=None):
    """
    Visualizes K-Means clustering results for RFM analysis using 2D and 3D scatter plots.

    Parameters:
    -----------
    rfm_df : pandas.DataFrame
        DataFrame containing the unscaled 'Recency', 'Frequency', and 'Monetary' columns.
    cluster_labels : array-like
        The array of cluster assignments generated by the K-Means model.
    cluster_names : dict, optional
        A dictionary mapping numeric cluster IDs to descriptive strings.
        Example: {0: 'Loyal Customers', 1: 'Dormant Leads', 2: 'At-Risk', 3: 'New Browsers'}
    """

    # 1. Prepare the dataframe for plotting
    plot_df = rfm_df.copy()
    plot_df["Cluster"] = cluster_labels

    # Determine the column to use for color grouping (hue)
    hue_column = "Cluster"
    if cluster_names:
        plot_df["Cluster_Name"] = plot_df["Cluster"].map(cluster_names)
        hue_column = "Cluster_Name"

    # Set seaborn visual style
    sns.set_theme(style="whitegrid")
    color_palette = "Set2"

    # ==========================================
    # 2. GENERATE 2D SCATTER PLOTS
    # ==========================================
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Plot 1: Frequency vs Monetary
    sns.scatterplot(
        data=plot_df,
        x="Frequency",
        y="Monetary",
        hue=hue_column,
        palette=color_palette,
        alpha=0.7,
        ax=axes[0],
    )
    axes[0].set_title("Frequency vs Monetary", fontsize=14, fontweight="bold")
    axes[0].set_xlabel("Frequency")
    axes[0].set_ylabel("Monetary")

    # Plot 2: Recency vs Frequency
    sns.scatterplot(
        data=plot_df,
        x="Recency",
        y="Frequency",
        hue=hue_column,
        palette=color_palette,
        alpha=0.7,
        ax=axes[1],
    )
    axes[1].set_title("Recency vs Frequency", fontsize=14, fontweight="bold")
    axes[1].set_xlabel("Recency")
    axes[1].set_ylabel("Frequency")

    # Plot 3: Recency vs Monetary
    sns.scatterplot(
        data=plot_df,
        x="Recency",
        y="Monetary",
        hue=hue_column,
        palette=color_palette,
        alpha=0.7,
        ax=axes[2],
    )
    axes[2].set_title("Recency vs Monetary", fontsize=14, fontweight="bold")
    axes[2].set_xlabel("Recency")
    axes[2].set_ylabel("Monetary")

    plt.tight_layout()
    plt.show()

    # ==========================================
    # 3. GENERATE 3D SCATTER PLOT
    # ==========================================
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    # Extract unique clusters to iterate through for the 3D plot legend
    unique_clusters = sorted(plot_df[hue_column].unique())
    cmap = plt.get_cmap(color_palette)

    # Plot each cluster iteratively to ensure the legend captures the names correctly
    for idx, cluster_val in enumerate(unique_clusters):
        subset = plot_df[plot_df[hue_column] == cluster_val]
        ax.scatter(
            subset["Recency"],
            subset["Frequency"],
            subset["Monetary"],
            color=cmap(idx),
            label=cluster_val,
            s=40,
            alpha=0.7,
            depthshade=True,
        )

    ax.set_xlabel("Recency")
    ax.set_ylabel("Frequency")
    ax.set_zlabel("Monetary")
    ax.set_title("3D Scatter Plot of RFM Clusters", fontsize=16, fontweight="bold")

    # Render legend
    ax.legend(title="Customer Segments" if cluster_names else "Clusters", loc="best")

    plt.show()


def plot_elbow_dbscan(data, min_pts):
    """
    Plot the k-distance graph (Elbow curve) to find the optimal epsilon for DBSCAN.

    This method calculates the distance from each point to its k-th nearest
    neighbor (where k = min_pts). The distances are sorted in ascending order
    and plotted. The "elbow" or "knee" of the curve (where the slope increases
    sharply) indicates the optimal epsilon value.

    Args:
        data (array-like): Preprocessed feature matrix.
            Should be a 2D array or DataFrame with shape (n_samples, n_features).
        min_pts (int): The chosen minPts value for DBSCAN. Defaults to 4.
            Used as the 'k' for finding nearest neighbors.

    Returns:
        None: Displays the k-distance plot inline.
    """
    # Initialize NearestNeighbors model
    neighbors = NearestNeighbors(n_neighbors=min_pts)
    neighbors_fit = neighbors.fit(data)

    # Calculate distance from each point to its min_pts nearest neighbors
    distances, indices = neighbors_fit.kneighbors(data)

    # Get the distance to the farthest point among the min_pts nearest neighbors (in the last column)
    # Then sort this distance array in ascending order
    k_distances = np.sort(distances[:, -1])

    # Plot the k-distance graph
    plt.figure(figsize=(10, 6))
    plt.plot(k_distances, color="#e74c3c", linewidth=2)
    plt.title(f"K-Distance Graph (Elbow Method for DBSCAN) - k={min_pts}", fontsize=14)
    plt.xlabel("Data Points sorted by distance", fontsize=12)
    plt.ylabel(f"{min_pts}-th Nearest Neighbor Distance ($\epsilon$)", fontsize=12)
    plt.grid(True, alpha=0.3)

    # Add padding to the Y-axis to better visualize the "elbow"
    plt.ylim(0, 1.0)

    plt.show()


def get_optimal_epsilon(data, min_pts):
    """
    Automatically calculate optimal epsilon based on elbow method (Kneedle algorithm).
    """
    # 1. Calculate distance
    neighbors = NearestNeighbors(n_neighbors=min_pts)
    neighbors_fit = neighbors.fit(data)
    distances, indices = neighbors_fit.kneighbors(data)
    k_distances = np.sort(distances[:, -1])

    # 2. Normalize X and Y to [0, 1]
    x = np.arange(len(k_distances))
    x_norm = (x - x.min()) / (x.max() - x.min())
    y_norm = (k_distances - k_distances.min()) / (k_distances.max() - k_distances.min())

    # 3. Calculate distance from each point to the line connecting the first and last points (y = x in normalized space)
    # The point with the largest distance is the elbow point
    distances_to_line = np.abs(x_norm - y_norm)
    elbow_index = np.argmax(distances_to_line)

    return k_distances[elbow_index]


# =============================================================================
# Clustering Functions
# =============================================================================


def run_kmeans(data, k):
    """
    Run K-Means clustering and return cluster labels.

    K-Means is a centroid-based algorithm that partitions data into k clusters
    by minimizing within-cluster variance.  It works well with spherical,
    similarly-sized clusters and is the primary baseline model for this project.

    Args:
        data (array-like): Preprocessed feature matrix (scaled RFM values).
        k (int): Number of clusters to create.

    Returns:
        np.ndarray: Array of cluster labels (0 to k-1) for each sample.
    """
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(data)
    return labels


def run_dbscan(data, eps, min_samples):
    """
    Run DBSCAN clustering and return cluster labels.

    DBSCAN (Density-Based Spatial Clustering of Applications with Noise) is
    a density-based algorithm that can discover clusters of arbitrary shape
    and automatically identifies noise/outlier points (labeled as -1).

    Unlike K-Means, DBSCAN does not require specifying the number of clusters
    in advance.  Instead, it uses two parameters:
      - eps: maximum distance between two points to be considered neighbors.
      - min_samples: minimum number of points to form a dense region (core point).

    Args:
        data (array-like): Preprocessed feature matrix (scaled RFM values).
        eps (float): Neighborhood radius. Defaults to 0.5.
        min_samples (int): Minimum points to form a cluster. Defaults to 5.

    Returns:
        np.ndarray: Array of cluster labels. Noise points are labeled -1.
    """
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    labels = dbscan.fit_predict(data)
    return labels


def run_hierarchical(data, n_clusters=4, linkage_method="ward"):
    """
    Run Agglomerative Hierarchical Clustering and return cluster labels.

    Agglomerative Hierarchical Clustering is a bottom-up approach that starts
    with each point as its own cluster and iteratively merges the closest pair
    of clusters until the desired number of clusters is reached.

    The linkage method determines how the distance between clusters is computed:
      - 'ward': Minimizes within-cluster variance (similar to K-Means objective).
      - 'complete': Uses the maximum distance between cluster members.
      - 'average': Uses the average distance between cluster members.
      - 'single': Uses the minimum distance between cluster members.

    Args:
        data (array-like): Preprocessed feature matrix (scaled RFM values).
        n_clusters (int): Number of clusters to create. Defaults to 4.
        linkage_method (str): Linkage criterion to use. Defaults to 'ward'.
            Must be one of 'ward', 'complete', 'average', 'single'.

    Returns:
        np.ndarray: Array of cluster labels (0 to n_clusters-1) for each sample.
    """
    model = AgglomerativeClustering(n_clusters=n_clusters, linkage=linkage_method)
    labels = model.fit_predict(data)
    return labels


# =============================================================================
# Dendrogram Visualization
# =============================================================================


def plot_dendrogram(data, method="ward", max_display=30):
    """
    Plot a dendrogram to visualize the hierarchical cluster structure.

    Computes a linkage matrix using scipy's linkage function and renders a
    truncated dendrogram.  This is useful for determining the natural number
    of clusters by inspecting where large jumps in merge distance occur.

    The dendrogram is truncated to show only the last `max_display` merges,
    making it readable even for large datasets.

    Args:
        data (array-like): Preprocessed feature matrix (scaled RFM values).
            Should be a 2D array or DataFrame with shape (n_samples, n_features).
        method (str): Linkage method for computing cluster distances.
            Defaults to 'ward'. Options: 'ward', 'complete', 'average', 'single'.
        max_display (int): Number of leaf nodes to display in the truncated
            dendrogram. Defaults to 30.

    Returns:
        None: Displays the dendrogram plot inline.
    """
    # Compute the full linkage matrix
    linked = linkage(data, method=method)

    # Plot the dendrogram (truncated for readability)
    plt.figure(figsize=(14, 7))
    dendrogram(
        linked,
        truncate_mode="lastp",
        p=max_display,
        leaf_rotation=90,
        leaf_font_size=10,
        show_contracted=True,
    )
    plt.title(f"Hierarchical Clustering Dendrogram ({method} linkage)", fontsize=14)
    plt.xlabel("Cluster Size (or Sample Index)", fontsize=12)
    plt.ylabel("Distance", fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()


# =============================================================================
# Evaluation Functions
# =============================================================================


def calculate_silhouette(data, labels):
    """
    Calculate the Silhouette Score for a set of cluster labels.

    The Silhouette Score measures how similar each point is to its own cluster
    (cohesion) compared to other clusters (separation).  Values range from
    -1 to +1:
      - +1: Points are well-matched to their cluster and poorly-matched to neighbors.
      -  0: Points are on the boundary between clusters.
      - -1: Points may be assigned to the wrong cluster.

    Edge cases handled:
      - If there are fewer than 2 unique labels, silhouette_score cannot be
        computed (it requires at least 2 clusters).  Returns -1 in this case.
      - If ALL labels are -1 (all noise, no clusters), returns -1.
      - If there is exactly 1 unique non-noise cluster, returns -1.

    Args:
        data (array-like): Preprocessed feature matrix used for clustering.
        labels (array-like): Cluster labels assigned to each sample.

    Returns:
        float: Silhouette Score in range [-1, 1], or -1 if the score
            cannot be computed (too few clusters).
    """
    # Count unique labels; silhouette_score requires at least 2 distinct clusters
    unique_labels = set(labels)

    # Edge case: all noise (-1 only) or only one cluster type present
    # sklearn's silhouette_score will raise an error if n_labels < 2
    # or if n_labels >= n_samples - 1, so we check first.
    if len(unique_labels) < 2 or (len(unique_labels) == 1 and -1 in unique_labels):
        return -1

    return silhouette_score(data, labels)
